### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by rebeccahughes** [react-native-fellowship/react-native-blur#21]
Are there any plans to add Android support?

**Comment by Kureev** [comment]
Sure, but I need to make some research first. Never worked on Android, need to figure out what exactly needs to be done for it. I'll keep you posted.

**Comment by Kureev** [comment]
Seems it require more efforts than I expected. The reason is that Android doesn't support blur out-of-box, so it leads us to use something like https://github.com/paveldudka/blurring for it. But I need some assistance form android developers to help me implementing it.

**Comment by KelseyRegan** [comment]
Hey Kureev, can we get an initial version of this component in Android that just puts a tinted view up?  That way we can still use it cross platform and we can work on a more advanced solution later.

**Comment by Kudo** [comment]
Just seen there is a https://github.com/kwaak/react-native-android-blurryoverlay

**Comment by fubar** [comment]
Just came across this well-written article about implementing a blur effect on Android. I'm not an Android dev myself but maybe it helps or inspires someone here.
http://developers.500px.com/2015/03/17/a-blurring-view-for-android.html

They also put their solution on github under MIT license:
https://github.com/500px/500px-android-blur

**Comment by williambout** [comment]
:+1: for Android Support.

**Comment by ericraio** [comment]
As a temporary solution, I did this.

BlurView.ios.js
```
'use strict';

import React, { Component, StyleSheet } from 'react-native';
import { BlurView } from 'react-native-blur';

var styles = StyleSheet.create({
  transparent: {
    backgroundColor: 'transparent'
  }
});

export default class extends Component {
  render() {
    return (
      <BlurView blurType="light" style={styles.transparent} {...this.props} >
        {this.props.children}
      </BlurView>
    );
  }
}
```

BlurView.android.js
```
  import React, { View, Component, StyleSheet } from 'react-native';
  import BlurryOverlay from 'react-native-android-blurryoverlay';


  var styles = StyleSheet.create({
    transparent: {
      backgroundColor: 'transparent'
    }
  });

  export default class extends Component {
    render() {
      return (
        <View {...this.props}>
>>        <BlurryOverlay radius={5} sampling={8} color="#00FFFF00" style={[{flex: 1, position: "absolute", left: 0, >
          {this.props.children}
        </View>
      );
    }
  }
```

src
```
// ....
import BlurView from '../components/BlurView';
// ....
export default class extends Component {
  render() {
    return (
      <BlurView style={styles.container}>
            <Text>Hello World</Text>
       </BlurView>
    )
  }
}
```

**Comment by mhollweck** [comment]
Does anyone have a working sample of BlurryOverlay?

**Comment by bymurat** [comment]
Android Support +1.

Regards.

**Comment by Wasseing** [comment]
Android support would be great !

**Comment by grabbou** [comment]
We are looking into this internally in one of our apps - chances are we submit a PR next week if we have time.

**Comment by alidawud** [comment]
Android Support +1.

Regards.

**Comment by ericraio** [comment]
@grabbou can't wait!

**Comment by cmcewen** [comment]
Here's one go - feedback appreciated! https://github.com/react-native-fellowship/react-native-blur/pull/59

**Comment by SudoPlz** [comment]
@grabbou Cant wait either. @cmcewen Thanks for that man. Lets see if it gets merged..!

**Comment by KGALLET** [comment]
+1

**Comment by dieguitoweb** [comment]
+1

**Comment by VinceBT** [comment]
+1

**Comment by Kureev** [comment]
Well, I think it's a time 😸 

Android support has been released in the new major version! 1.0.0 is out! Thanks, @cmcewen!

**Comment by sompylasar** [comment]
@Kureev Could you please update the README with a cross-platform (ios + android) example, the Android section is very confusing because the component is not coherent.

**Comment by cmcewen** [comment]
@sompylasar unfortunately it's not possible to use the same code on both platforms. iOS has a native `UIVisualEffectView` but Android has no platform support for easily blurring a view https://developers.500px.com/a-blurring-view-for-android-7f33d41a047d. I wrapped that library which I believe is better than nothing right now, but if you have suggestions on how to unify the API I am happy to take them

**Comment by sompylasar** [comment]
@cmcewen Have you seen this implementation: https://github.com/Dimezis/BlurView ? Looks like it finds the views to blur automatically, but I may be wrong. The author says that in contrast to 500px's implementation, his one automatically determines when to redraw.

Regardless of the API unification, there should be an option to use the same React Native component (with different props) cross-platform, and I expect an example of such usage in the README.

**Comment by sompylasar** [comment]
@cmcewen Sorry, I missed the [examples folder](https://github.com/react-native-fellowship/react-native-blur/tree/master/examples/Basic), there was no link to it from the README.

I'm not developing anything for React Native now, just following some resources and relating modules to each other for future use if I some day start doing mobile development with React Native (I'm a web application engineer now using React), so I won't be able to PR anything because I don't have all the development environment installed.

I stumbled upon [the module I referenced](https://github.com/Dimezis/BlurView) on [a local software community website](https://habrahabr.ru/post/302552/) and thought it could be a good fit for React Native Blur (this [was even before](https://habrahabr.ru/post/302552/#comment_9643962) the [official approval of the 500px solution](https://github.com/react-native-fellowship/react-native-blur/issues/21#issuecomment-225714325), but the author wasn't interested enough to suggest his module to React Native community).

I don't know if it's easier to use, only that the author told me in the comment about the auto-redraw feature that was missing from 500px's implementation.
