### ISSUE TITLE
Is it possible to set tintColor

### ISSUE THREAD

**Issue by kinhunt** [react-native-fellowship/react-native-blur#35]
It would be cool to be able to add tintColor to the UIVisualEffectView. Any chance?

something like this

http://i.stack.imgur.com/FUJuH.png

**Comment by AlexGustafsson** [comment]
I've done this in the past by having a colored semi-transparent element showing over the blurred element. It works well. But of course, a built in way to achieve it would be really appreciated.

**Comment by Kureev** [comment]
Unfortunately, Apple doesn't provide any config for it. It's possible using OpenGL, but this component relying on native Apple implementation.
