### ISSUE TITLE
Couldn't blur, gives backgroundColor

### ISSUE THREAD

**Issue by sercanov** [react-native-fellowship/react-native-blur#36]
I've used the BlurView in my previous project, It was working as expected but I couldn't make it work for my current project. 

I've tried like in the example. Tried BlurView on both for parent and child component, it's the same.
The gray area in the screenshot should be blurred.

![ekran resmi 2015-11-29 00 29 20](https://cloud.githubusercontent.com/assets/10291644/11454322/6feaf458-9630-11e5-9bb5-d61254986c52.png)

**Comment by Kureev** [comment]
I'm a bit confused: how you expect solid color to be blurred?

**Comment by sercanov** [comment]
@Kureev I wasn't trying to blur solid color, the grey area is actually a Image component inside of a BlurView. It's the image on the example project. Here is the code ;

     `<Image source={{uri:'http://iphonewallpapers-hd.com/thumbs/firework_iphone_wallpaper_5-t2.jpg'}} style={{flex:1}}>
       <BlurView blurType="dark" style={{flex:1}}>
    
       </BlurView>
    </Image>`

**Comment by ehd** [comment]
@sercanov I think you need to set `backgroundColor: 'transparent'` on the `BlurView`. @kureev, maybe that's something we could add to the README?

**Comment by sercanov** [comment]
oh @ehd that solves it. Thanks.

**Comment by Kureev** [comment]
@ehd I think that's something we can add automatically by default. Do you want to make a PR?

**Comment by ehd** [comment]
@Kureev Sure! So [https://github.com/react-native-fellowship/react-native-blur/blob/4c764ac6a3c3a008ee7739980e4e5e6585af8413/src/BlurView.js#L9] we would change `BlurView` (and similarly `VibrancyView`) as such?

``` js
class BlurView extends Component {
  render() {
    return (
      <NativeBlurView
        {...this.props}
        style={{
          backgroundColor: 'transparent',
          ...this.props.style
        }}
      />;
    )
  }
}
```

Which to my knowledge would set `backgroundColor: 'transparent'` as an overridable default.

**Comment by Kureev** [comment]
yep, exactly! @ehd
