### ISSUE TITLE
Fatal exception in 0.7.7

### ISSUE THREAD

**Issue by jamesfzhang** [react-native-fellowship/react-native-blur#39]
I'm getting this error after installing 0.7.7. Works just fine in 0.7.6.

Unhandled JS Exception: In this environment the target of assign MUST be an object.This error is a performance optimization and not spec compliant.

I'm guessing it's because of https://github.com/react-native-fellowship/react-native-blur/commit/3c0fd0d6ba7acde6119487bcfa7eca0215bb44d7

**Comment by dubert** [comment]
:+1:

**Comment by Kureev** [comment]
oh, it seems we need to add `style` to defaultProps

**Comment by viix** [comment]
same here.

**Comment by Kureev** [comment]
I'm going to push a major release soon. So I'm not going to patch a version in npm specifically for this one. Stay tuned.

**Comment by ehd** [comment]
Thanks for fixing this!
