### ISSUE TITLE
Release 0.7.7 throws fatal error "target of assign MUST be an object"

### ISSUE THREAD

**Issue by natorojr** [react-native-fellowship/react-native-blur#43]
![screen shot 2015-12-29 at 10 44 46 am](https://cloud.githubusercontent.com/assets/1237186/12040112/ed4d962e-ae1a-11e5-8c84-8df700b138ca.png)

Line: https://github.com/react-native-fellowship/react-native-blur/blob/v0.7.7/src/BlurView.js#L12

Environment:
    react-native: 0.13.2,
    babel: 5.8.34

Note, it was working fine w/ version 0.7.6

I have another project using react-native 0.17.0 w/ Babel 6, I'll confirm whether or not they same error happens there and update this issue.

**Comment by natorojr** [comment]
Confirmed same error w. react-native 0.17.0 and Babel 6.

**Comment by realjamie** [comment]
+1

**Comment by pjcabrera** [comment]
+1

**Comment by Kureev** [comment]
It's probably my bad. I need to make a table with RN version to some-rnf-plugins matching. Latest versions relies on babel 6 and rn 0.16+. Sorry for not informing you about it

**Comment by Kureev** [comment]
Oops, missclick

**Comment by natorojr** [comment]
@Kureev  Thanks for looking into it. Just wanted to reiterate that I was able to reproduce the same error with React Native 0.17.0 and Babel 6.

**Comment by tuneZola** [comment]
+1

**Comment by cpunion** [comment]
I reproduced the same problem, seems the reason is:

```javascript
class BlurView extends Component {
  render() {
    return (
      <NativeBlurView
        {...this.props}
        style={{
          backgroundColor: 'transparent'
          ...this.props.style                            // <<--- this line
        }}
      />
    );
  }
}
```

When I pass a `Stylesheet` object, this.props.style is a number. I fixed it with:

```javascript
class BlurView extends Component {
  render() {
    return (
      <NativeBlurView
        {...this.props}
        style={[
          {
            backgroundColor: 'transparent'
          },
          ...this.props.style
        ]}
      />
    );
  }
}
```

**Comment by viix** [comment]
#40 fix the issue, just not go to npm
@Kureev maybe push to npm after test

**Comment by cpunion** [comment]
@viix Great!

+1

**Comment by Kureev** [comment]
Try `0.7.8` please

**Comment by tuneZola** [comment]
Looks like its fixed, TX.

**Comment by natorojr** [comment]
Sorry for the delayed response. Confirmed fixed.
