### ISSUE TITLE
Add cocoapods support

### ISSUE THREAD

**Issue by adrienbrault** [react-native-fellowship/react-native-blur#47]

**Comment by grabbou** [comment]
Last time I proposed that `Kureev` wasn't happy about it and I think that haven't changed since then, esp. given the fact we maintain rnpm. But I am leaving that up to him.

**Comment by Kureev** [comment]
What's the point for this now? I'd recommend to use `rnpm` for this purpose instead :smile_cat:

**Comment by adrienbrault** [comment]
I added a new scheme to my project, and could not get the project to compile while using rnpm for react-native-blur.
Adding a podspec to the repo and using cocoapods fixed my build issues https://github.com/react-native-fellowship/react-native-blur/compare/master...adrienbrault:patch-1

**Comment by Kureev** [comment]
Maybe it's not a scope of this story, but can you give me some insights why `rnpm` failed, please? We're looking forward to improve it and solving issues like that is the best way to build an awesome project :stuck_out_tongue_winking_eye:

**Comment by grabbou** [comment]
To me it doesn't matter. Pod spec is just one file, Cocoapods is just native package manager and I don't see any points against support it. The more choice, the better, especially given the fact Cocoapods pod specs are files you never modify in the future.

When there's PR - I am up to merging one.

**Comment by billinghamj** [comment]
I'd prefer to stick with Cocoapods also. React Native is just a part of my app - the app isn't solely React Native. Thus, I'd much rather use the standard iOS packaging tools as-is.

**Comment by adbl** [comment]
@adrienbrault I see that you already have a patch for this at https://github.com/adrienbrault/react-native-blur/commits/patch-1 please PR it =)

**Comment by Kureev** [comment]
Done.
