### ISSUE TITLE
rnpm doesn't install ios dependencies

### ISSUE THREAD

**Issue by lrettig** [react-native-fellowship/react-native-blur#49]
I ran:

```
$ npm install react-native-blur
FooProject@0.0.1 /Users/foo/FooProject
└── react-native-blur@0.7.9  extraneous
$ rnpm -V
1.4.1
$ rnpm link
rnpm info Linking react-native-image-picker android dependency
rnpm info Android module react-native-image-picker is already linked
```

in my project folder. It didn't install any iOS dependencies. Had to do this the old fashioned way. Am I doing something wrong?

Thanks

**Comment by grabbou** [comment]
Hey! Don't forget to --save your dependency into package.json so that rnpm is aware of it ;) let me know if that solves the problem!

**Comment by lrettig** [comment]
That worked. Thank you!

**Comment by faceyspacey** [comment]
doesn't work for me either, but I'm saving the dependencies.

**Comment by Kureev** [comment]
@faceyspacey try using `rnpm install react-native-blur`

**Comment by baurine** [comment]
@Kureev I met the same problem, and `rnpm install react-native-blur` doesn't work.

**Comment by Kureev** [comment]
`rnpm` is a part of `react-native` now. Please, consider using `react-native install` instead
