### ISSUE TITLE
blur not working on iPad Retina/iPad2

### ISSUE THREAD

**Issue by andyfenelon** [react-native-fellowship/react-native-blur#51]
blur effect doesn't appear to be working on some iPad devices in simulation

NOT working 
- iPad Retina
- iPad 2

working on 
- iPad pro 
- iPad Air

this was the image i used as a full screen bg, incase image size has anything to do with it.
http://img00.deviantart.net/8910/i/2011/225/a/7/night_city_lights_by_ati711-d46fp5i.jpg

i thought it might be this size so i tried it with a larger
http://www.fyqyfz.com/data/uploads/15/334042-citylights-blur.jpg

still getting it specific devices.

**Comment by Kureev** [comment]
It's available in iOS 8.0 and later, doesn't matter which device you have.

**Comment by markrickert** [comment]
I'm seeing this same exact issue on iPad 2 devices (simulator). I build the app for iPhone and the blur view works, but when compiling and running on iPad 2 it just shows a grey box.

**Comment by markrickert** [comment]
OK, So i think i found the "solution"... which is not a solution, just how things work...

Quoted From http://asciiwwdc.com/2014/sessions/419

> So let's take a look how the blur performs on the various devices.
> 
> So again this is the fullscreen blur that I used before and I met it as well on iPad 3, 3rd generation.
> 
> And as you can see the iPad 3rd generation performs much worse than the iPad Air.
> 
> In the case of the extra light blur the timing is 18.15ms, so we can't render at 60 hertz this type of blur on iPad Air.
> 
> And for light and dark we are around 14.5ms, which leaves us about 2ms for UI, which is not really enough for rendering any compelling UI.
> 
> So the decision we made on iOS 7 RA was that we would disable the blur on certain devices and the iPad 3rd generation is one of these devices.
> 
> And this the performance on the iPad 3rd generation changes to this.
> 
> You basically just apply a tint layer on top so that we can make sure that legibility is the same as without the BlurEffect.
> 
> So, and to reiterate on what devices we don't blur and that we only do the tinting on the iPad 2 and iPad 3rd generation, we just apply the tint and we skip the blur steps.
> 
> On iPad 4th generation, iPad Air, iPad Mini, iPad Mini with retina display, iPhones and the iPod touch we do both the blur and the tinting.
> 
> So, in summary for the UIVisualEffectView with UIBlurEffect, UIBlurEffect have multiple onscreen passes depending on the style.
> 
> Only dirty regions are redrawn.

As you can see from the Apple engineer's talk, the blurs will only render on a iPad 4th generation, iPad Air, iPad Mini, iPad Mini with retina display.

What they're doing on the iPad 2 (which is what I'm seeing in my implementation) is a simple tinting of the window and not applying a blur for performance reasons.

I'd say this issue can be closed, however, maybe adding a note to the readme that the blurs won't work on older iPad devices.

**Comment by andyfenelon** [comment]
ahh. thanks
