### ISSUE TITLE
Is it possible to use borderRadius on BlurView? 

### ISSUE THREAD

**Issue by teebolt** [react-native-fellowship/react-native-blur#58]
Doesn't appear to be taking borderRadius even when I have BlurView nested inside a <View> and put a borderRadius on the View.

**Comment by kaifaust** [comment]
+1

**Comment by kaifaust** [comment]
`overflow: 'hidden'` on the parent container does the trick.

**Comment by DanPHP7** [comment]
how to set border radius on bottom left and right ?

**Comment by DasArthur** [comment]
> how to set border radius on bottom left and right ?

Firstly create main <View> which will hold all borderRadius such as bottom left and right and inside in that View just add BlurView without borderRadius.

Also add overflow: 'hidden' to the View to get the borderRadius working

Example:
~~~
<View style={{ 
            borderRadius: 9, 

            borderTopRightRadius: 0, 
            borderTopLeftRadius:0, 
            overflow: "hidden",  
            flex: 1,  
            width: "100%",  
            backgroundColor: "transparent". 
        }}>
        <BlurView
            blurType={"light"}
            blurAmount={20}
            reducedTransparencyFallbackColor="rgba(37,42,54,.25)"
            style={[
                {  
                    width: "100%", 
                    height: 100,
                    backgroundColor: "rgba(37,42,54,0.25)",
                }
            ]}
        >
            {/* ADD CONTENT */}
        </BlurView>
</View>
~~~
