### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by akaiworld** [react-native-fellowship/react-native-blur#60]
Just show red borders around the view and no blur at all =((

**Comment by Kureev** [comment]
have you linked a native part to your project according docs?

**Comment by akaiworld** [comment]
I exactly followed the 1-4 step installation process (as written here https://github.com/react-native-fellowship/react-native-blur#installation ) and also re-checked by examples, but did not get the effect, only red borders.

**Comment by caledhwa** [comment]
So, I had this same problem. If you download rnpm and link the library it should link it correctly.

run the link command where your package.json lives.

```
npm install -g rnpm
rnpm link
```

**Comment by MichielDeMey** [comment]
Had the same problem, you have to recompile after linking using `rnpm link`.
Simply reloading the app won't have any effect.

**Comment by Kureev** [comment]
@MichielDeMey answer seems to be valid: install react-native-blur using rnpm and re-run your app.
