### ISSUE TITLE
how to switch the blurType between 'light/dark/...' and 'none'

### ISSUE THREAD

**Issue by 12343954** [react-native-fellowship/react-native-blur#62]
how to switch the blurType between 'light/dark/...' and 'none' ?

i want to switch ,but not static effect

thank you

**Comment by Kureev** [comment]
What you mean by switch?

If you want a transition, then there is no support for it (afaik apple doesn't provide us any hooks for animating blur, let me know if I'm wrong).

If you're talking about switching a type of blur, then it can be done as a usual react component prop change.

**Comment by wokalski** [comment]
@Kureev I think there's a very non-ideal, hacky, and non idiomatic but working solution when it comes to animations. We could add an optional prop let's say `animation` which is an object that contains two fields:
- `duration`
- `type` - 'blurIn` or `blurOut`

When the native component receives this prop it animates the blur view or just displays it if the prop is not set.

**Comment by Kureev** [comment]
I'm not sure if we can animate this. As I mentioned back in the README, this implementation is based on `UIVisualEffectView` which doesn't support this effect.

**Comment by wokalski** [comment]
It does! I doing a similar thing myself and it does work. It is supported since iOS 9. The API looks like this:
```
UIVisualEffectView *view = [[UIVisualEffectView alloc] init];
...
...
[UIView animateWithDuration:0.25 animations:^{
      blurView.effect = nil;
}];
```

**Comment by Kureev** [comment]
Oh, didn't knew that, thanks!

Could you submit a PR? I would be happy to merge it in!

**Comment by wokalski** [comment]
Sure, I'll play with it later this week. 👍

**Comment by wokalski** [comment]
This is what I came up with for a similar problem in my app. This API has to be imperative due to the nature of `UIKit`.

The JavaScript API looks like this:

```js
// blurView is a reference to a component
blurView.fadeIn(
  duration,
  callback
)
```

<details>
  <summary>Objective-C implementation</summary>
  ```objc
RCT_EXPORT_METHOD(fadeIn:(nonnull NSNumber *)reactTag
                   duration:(CGFloat) duration
                   completion:(RCTResponseSenderBlock)callback) {
   [self.bridge.uiManager addUIBlock:^(RCTUIManager *uiManager, NSDictionary<NSNumber *,UIView *> *viewRegistry) {
     AnimatedBlurView *view = (AnimatedBlurView *)viewRegistry[reactTag];
     if ([view isKindOfClass:[AnimatedBlurView class]]) {
       view.blurView.effect = nil;
       [UIView animateWithDuration:duration animations:^{
         view.blurView.effect = [view effect];
       } completion:^(BOOL finished) {
         if (callback) {
           callback(@[]);
         }
       }];
     }
   }];
 }

// Similar one for fadeOut
 
```
</details>

**Comment by Kureev** [comment]
LGTM! I have to try it on my machine first, but I don't see any issues so far

**Comment by wokalski** [comment]
@Kureev don't bother! If you think the API is OK, I will submit a proper PR.

**Comment by Kureev** [comment]
Well, I'd like to propose something, actually:

Instead of using imperative API we can expose <AnimatedBlurView/> and <AnimatedVibrancyView/> with animation parameters required. What do you think?

P.S. What about opening a new issue and continue discussion there?
