### ISSUE TITLE
Android Build: Dependency Issue - Could not find com.fivehundredpx:blurringview:1.0.0

### ISSUE THREAD

**Issue by caledhwa** [react-native-fellowship/react-native-blur#68]
Here's my error after:

```
npm install react-native-blur@1.0.0 --save
rnpm link
```

And a:

```
react-native run-android
```

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.fivehundredpx:blurringview:1.0.0.
     Searched in the following locations:
         file:/Users/kqn032/dev/Magneto/node_modules/react-native/android/com/fivehundredpx/blurringview/1.0.0/blurringview-1.0.0.pom
         file:/Users/kqn032/dev/Magneto/node_modules/react-native/android/com/fivehundredpx/blurringview/1.0.0/blurringview-1.0.0.jar
         file:/usr/local/opt/android-sdk/extras/android/m2repository/com/fivehundredpx/blurringview/1.0.0/blurringview-1.0.0.pom
         file:/usr/local/opt/android-sdk/extras/android/m2repository/com/fivehundredpx/blurringview/1.0.0/blurringview-1.0.0.jar
```

I assume I'm missing something that may not be in your npm package?

**Comment by caledhwa** [comment]
So, the `readme` says you must add things to your Android build. However, it also says that installation can be `rnpm link` - Do I have to do both? Am I asking a question here or does the rnpm link not cover?

**Comment by caledhwa** [comment]
Closing this issue... Just that your Readme is not clear about "installation" - I might suggest a PR to help with that. :)

**Comment by CharlesMangwa** [comment]
Did you actually solved this issue plz?

**Comment by Kureev** [comment]
Unfortunately, I'm quite busy these days. I hope @cmcewen can help you to sort it out!

P.S. RNPM can't handle Android part for this dependency. There are some things that we don't support

**Comment by caledhwa** [comment]
Hey @Kureev - no problem. Since I was led a bit astray by the readme in this regard, maybe I'll fork and submit a PR just updating the install notes so it's clear about the role of `rnpm link` and the manual edits of the gradle file. I totally understand being busy. That's also why I closed the issue once I realized that if you simply make the edits in the gradle file it should work fine. @CharlesMangwa - I didn't fix/test it. But I'm pretty sure it will work fine if you follow the instructions under the Android section of the readme.

**Comment by cmcewen** [comment]
@caledhwa that'd be greatly appreciated! I wasn't sure actually about whether `rnpm` could modify the app `build.gradle` but it sounds like it can't.

**Comment by CharlesMangwa** [comment]
Thanks @caledhwa for your tips, I'll try that! Actually @cmcewen, with `nrpm`, when I use `rnpm install <module-name>`, it can install & link everything automatically and even modified the `build.gradle`. But for some reason it doesn't work with `react-native-blur`

**Comment by caledhwa** [comment]
There are only specific things that RNPM link can do. Some of these edits would require a plug in.

**Comment by CharlesMangwa** [comment]
Thanks again, that's good to know.

**Comment by sirwoetang** [comment]
Usually packages are added to the settings.gradle file as well, like such:
```
include ':react-native-blur
project(':react-native-blur').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-blur/android')
```
This removes that error you are getting, but gives me a red outline element on the app, saying the native component could not be found.

**Comment by braco** [comment]
Looks like the android gradles have changed, so the README isn't applicable anymore.
