### ISSUE TITLE
red border, no vibrancy/blur

### ISSUE THREAD

**Issue by brumm** [react-native-fellowship/react-native-blur#73]
Using your example, both Blur- and VibrancyView seem to have a transparent background, and a red border. No other errors in the console.

**Comment by Kureev** [comment]
Hi @brumm! Seems you forgot to link a native part of the module. To make it easier for people, we created [rnpm](http://github.com/rnpm/rnpm). If you're using latest React Native, you can also use `react-native link`.

**Comment by brumm** [comment]
Weird, I could've sworn that I did link it, I'll check again.

**Comment by brumm** [comment]
Not sure what happened, but it works now :) Thanks for your time!

**Comment by luco** [comment]
@Kureev Hey!
I already linked and still not working:

![image](https://cloud.githubusercontent.com/assets/246373/18763891/964d2418-80e5-11e6-8791-8834f1f8fa9f.png)


My code:

```
 <View style={styles.row}>
        <BlurView shouldRasterizeIOS={false} blurType="light" style={{flex: 1}}>
           <TouchableHighlight onPress={this._onPressButton} style={styles.rowButton}>
            
              <View>
                  
              <Text>Test</Test>
                 
              </View>

            </TouchableHighlight>
           </BlurView>
      </View>
```

**Comment by Kureev** [comment]
The only thing I can say that you didn't link it properly. This red border tells you that your native component is not found. Consider removing the plugin and linking it using `react-native link`

**Comment by breadadams** [comment]
Just ran into this now. ~~It seems `react-native link` doesn't pick up on the module. I had to run `rnpm link react-native-blur` for it to link correctly~~. I forgot the `--save` flag while installing... :facepalm: Working nicely!

**Comment by AvishyBD** [comment]
just ran into it now - deleting the app on the phone, and react-native run-ios again seemed to do the trick...
